-- ═══════════════════════════════════════════════════════════════
-- AgroPlanner · Diagnóstico de esquema (SÓLO LECTURA)
-- ═══════════════════════════════════════════════════════════════
-- Dice qué le falta a esta base respecto del esquema esperado.
--
-- NO ESCRIBE NADA. Ni una tabla temporal: son todas consultas. Se puede
-- correr en producción sin backup y sin consecuencias.
--
-- ANTES DE CORRERLO: en el panel de la izquierda de phpMyAdmin hacé clic
-- en tu base (u515247413_agroplanner o como se llame), de modo que el
-- encabezado la muestre seleccionada. Si se corre sin base elegida,
-- phpMyAdmin queda parado en information_schema y todo devuelve vacío o
-- da error de permisos — que no es que falte algo, es que está mirando
-- la base equivocada. La primera consulta te avisa si pasa eso.
--
-- Correrlo ANTES que esquema_completo.sql. Si todo vuelve vacío, la
-- base ya está al día y no hace falta correr nada más.
-- ═══════════════════════════════════════════════════════════════

-- Portón: tiene que decir OK y mostrar TU base, no information_schema.
SELECT VERSION() AS motor,
       COALESCE(DATABASE(), '(ninguna)') AS base_seleccionada,
       IF(DATABASE() IS NULL OR DATABASE() IN ('information_schema','mysql','performance_schema'),
          'PARA: elegi tu base en el panel izquierdo y corre esto de nuevo',
          'OK, segui') AS estado;

-- Cuántas de las 30 tablas esperadas existen.
SELECT COUNT(*) AS tablas_presentes, 30 AS tablas_esperadas
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_TYPE = 'BASE TABLE'
  AND TABLE_NAME IN ('users', 'cultivos', 'lotes', 'depositos', 'alquileres', 'cotizaciones_siogranos', 'feedlot_alimentos', 'feedlot_costos_fijos', 'feedlot_lotes', 'ganaderia_egresos', 'ganaderia_egresos_conceptos', 'ganaderia_inventario', 'ganaderia_movimientos', 'ganaderia_pesadas', 'ganaderia_reproductivo', 'insumos', 'lote_historial_campanas', 'motor_consultas_fallidas', 'motor_preferencias', 'operacion_insumos', 'operaciones', 'produccion_ventas', 'tambo_calidad', 'tambo_dif_inventario', 'tambo_dolar_mes', 'tambo_egresos', 'tambo_egresos_conceptos', 'tambo_produccion', 'tambo_rodeo', 'tambo_ventas_carne');

-- Cuáles faltan, por nombre.
SELECT t.nombre AS tabla_faltante FROM (
    SELECT 'users' AS nombre
    UNION ALL SELECT 'cultivos' AS nombre
    UNION ALL SELECT 'lotes' AS nombre
    UNION ALL SELECT 'depositos' AS nombre
    UNION ALL SELECT 'alquileres' AS nombre
    UNION ALL SELECT 'cotizaciones_siogranos' AS nombre
    UNION ALL SELECT 'feedlot_alimentos' AS nombre
    UNION ALL SELECT 'feedlot_costos_fijos' AS nombre
    UNION ALL SELECT 'feedlot_lotes' AS nombre
    UNION ALL SELECT 'ganaderia_egresos' AS nombre
    UNION ALL SELECT 'ganaderia_egresos_conceptos' AS nombre
    UNION ALL SELECT 'ganaderia_inventario' AS nombre
    UNION ALL SELECT 'ganaderia_movimientos' AS nombre
    UNION ALL SELECT 'ganaderia_pesadas' AS nombre
    UNION ALL SELECT 'ganaderia_reproductivo' AS nombre
    UNION ALL SELECT 'insumos' AS nombre
    UNION ALL SELECT 'lote_historial_campanas' AS nombre
    UNION ALL SELECT 'motor_consultas_fallidas' AS nombre
    UNION ALL SELECT 'motor_preferencias' AS nombre
    UNION ALL SELECT 'operacion_insumos' AS nombre
    UNION ALL SELECT 'operaciones' AS nombre
    UNION ALL SELECT 'produccion_ventas' AS nombre
    UNION ALL SELECT 'tambo_calidad' AS nombre
    UNION ALL SELECT 'tambo_dif_inventario' AS nombre
    UNION ALL SELECT 'tambo_dolar_mes' AS nombre
    UNION ALL SELECT 'tambo_egresos' AS nombre
    UNION ALL SELECT 'tambo_egresos_conceptos' AS nombre
    UNION ALL SELECT 'tambo_produccion' AS nombre
    UNION ALL SELECT 'tambo_rodeo' AS nombre
    UNION ALL SELECT 'tambo_ventas_carne' AS nombre
) t
LEFT JOIN information_schema.TABLES x
       ON x.TABLE_SCHEMA = DATABASE() AND x.TABLE_NAME = t.nombre
WHERE x.TABLE_NAME IS NULL;

-- ───────────────────────────────────────────────────────────────
-- PARTE 5 · Verificación. Correr al final.
-- ───────────────────────────────────────────────────────────────
-- Compara la base contra el esquema esperado y muestra lo que no
-- coincida. Las PARTES 2 a 4 arreglan lo que saben arreglar; esto
-- delata cualquier otra diferencia en vez de dejarla pasar callada.
--
-- El esquema esperado va embebido en la consulta, no en una tabla
-- auxiliar: crearla exige permisos de CREATE y falla si phpMyAdmin no
-- tiene tu base seleccionada. Así no hace falta escribir nada.

-- Lo que falta o no coincide. VACÍO = la base está como tiene que estar.
SELECT e.tabla, e.columna, e.tipo AS esperado,
       COALESCE(c.COLUMN_TYPE, '(no existe)') AS encontrado
FROM (
        SELECT 'users' AS tabla, 'id' AS columna, 'int(11)' AS tipo
        UNION ALL SELECT 'users', 'username', 'varchar(50)'
        UNION ALL SELECT 'users', 'email', 'varchar(100)'
        UNION ALL SELECT 'users', 'password_hash', 'varchar(255)'
        UNION ALL SELECT 'users', 'role', 'enum(''admin'',''user'')'
        UNION ALL SELECT 'users', 'status', 'enum(''pending'',''active'')'
        UNION ALL SELECT 'users', 'created_at', 'timestamp'
        UNION ALL SELECT 'users', 'has_agricultura', 'tinyint(1)'
        UNION ALL SELECT 'users', 'has_tambo', 'tinyint(1)'
        UNION ALL SELECT 'users', 'has_ganaderia', 'tinyint(1)'
        UNION ALL SELECT 'users', 'reset_token', 'varchar(255)'
        UNION ALL SELECT 'users', 'reset_expires', 'datetime'
        UNION ALL SELECT 'users', 'solo_lectura', 'tinyint(1)'
        UNION ALL SELECT 'cultivos', 'id', 'int(11)'
        UNION ALL SELECT 'cultivos', 'lote_id', 'int(11)'
        UNION ALL SELECT 'cultivos', 'nombre', 'varchar(100)'
        UNION ALL SELECT 'cultivos', 'fecha_siembra', 'date'
        UNION ALL SELECT 'cultivos', 'fecha_cosecha_esperada', 'date'
        UNION ALL SELECT 'cultivos', 'estado', 'enum(''activo'',''cosechado'',''perdido'')'
        UNION ALL SELECT 'cultivos', 'created_at', 'timestamp'
        UNION ALL SELECT 'cultivos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'cultivos', 'ciclo', 'varchar(50)'
        UNION ALL SELECT 'lotes', 'id', 'int(11)'
        UNION ALL SELECT 'lotes', 'nombre', 'varchar(100)'
        UNION ALL SELECT 'lotes', 'superficie', 'decimal(10,2)'
        UNION ALL SELECT 'lotes', 'ubicacion', 'varchar(255)'
        UNION ALL SELECT 'lotes', 'tipo_suelo', 'varchar(100)'
        UNION ALL SELECT 'lotes', 'created_at', 'timestamp'
        UNION ALL SELECT 'lotes', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'lotes', 'latitud', 'decimal(10,8)'
        UNION ALL SELECT 'lotes', 'longitud', 'decimal(11,8)'
        UNION ALL SELECT 'lotes', 'tenencia', 'enum(''propio'',''alquilado'')'
        UNION ALL SELECT 'lotes', 'costo_alquiler_tns_ha', 'decimal(14,4)'
        UNION ALL SELECT 'lotes', 'campania', 'varchar(50)'
        UNION ALL SELECT 'lotes', 'cultivo_actual', 'varchar(100)'
        UNION ALL SELECT 'depositos', 'id', 'int(11)'
        UNION ALL SELECT 'depositos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'depositos', 'nombre', 'varchar(100)'
        UNION ALL SELECT 'depositos', 'descripcion', 'varchar(255)'
        UNION ALL SELECT 'depositos', 'ubicacion', 'varchar(255)'
        UNION ALL SELECT 'depositos', 'created_at', 'timestamp'
        UNION ALL SELECT 'alquileres', 'id', 'int(11)'
        UNION ALL SELECT 'alquileres', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'alquileres', 'lote_id', 'int(11)'
        UNION ALL SELECT 'alquileres', 'cultivo_id', 'int(11)'
        UNION ALL SELECT 'alquileres', 'nivel_imputacion', 'enum(''lote'',''cultivo'',''campania'')'
        UNION ALL SELECT 'alquileres', 'campania', 'varchar(50)'
        UNION ALL SELECT 'alquileres', 'fecha_pago', 'date'
        UNION ALL SELECT 'alquileres', 'monto_pagado', 'decimal(14,4)'
        UNION ALL SELECT 'alquileres', 'moneda', 'enum(''USD'',''ARS'')'
        UNION ALL SELECT 'alquileres', 'notas', 'text'
        UNION ALL SELECT 'alquileres', 'created_at', 'timestamp'
        UNION ALL SELECT 'cotizaciones_siogranos', 'id', 'int(11)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'fecha', 'date'
        UNION ALL SELECT 'cotizaciones_siogranos', 'cultivo', 'varchar(50)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'producto_id', 'varchar(30)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'zona', 'varchar(80)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'zona_id', 'varchar(10)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'precio_promedio', 'decimal(12,2)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'precio_minimo', 'decimal(12,2)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'precio_maximo', 'decimal(12,2)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'precio_modal', 'decimal(12,2)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'moneda', 'varchar(5)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'fecha_actualizacion', 'datetime'
        UNION ALL SELECT 'feedlot_alimentos', 'id', 'int(11)'
        UNION ALL SELECT 'feedlot_alimentos', 'lote_id', 'int(11)'
        UNION ALL SELECT 'feedlot_alimentos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'feedlot_alimentos', 'fase', 'enum(''invernada'',''engorde'')'
        UNION ALL SELECT 'feedlot_alimentos', 'nombre', 'varchar(100)'
        UNION ALL SELECT 'feedlot_alimentos', 'kg_x_dia', 'decimal(8,3)'
        UNION ALL SELECT 'feedlot_alimentos', 'precio_kg', 'decimal(10,2)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'id', 'int(11)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'lote_id', 'int(11)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'concepto', 'varchar(100)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'categoria', 'varchar(30)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'cantidad', 'decimal(10,2)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'precio_unitario', 'decimal(14,2)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'monto_mensual', 'decimal(14,2)'
        UNION ALL SELECT 'feedlot_lotes', 'id', 'int(11)'
        UNION ALL SELECT 'feedlot_lotes', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'feedlot_lotes', 'nombre', 'varchar(100)'
        UNION ALL SELECT 'feedlot_lotes', 'fecha_inicio', 'date'
        UNION ALL SELECT 'feedlot_lotes', 'cant_animales', 'int(11)'
        UNION ALL SELECT 'feedlot_lotes', 'pct_invernada', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'pct_engorde', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'kg_entrada_inv', 'decimal(8,2)'
        UNION ALL SELECT 'feedlot_lotes', 'kg_salida_inv', 'decimal(8,2)'
        UNION ALL SELECT 'feedlot_lotes', 'dias_invernada', 'int(11)'
        UNION ALL SELECT 'feedlot_lotes', 'kg_entrada_eng', 'decimal(8,2)'
        UNION ALL SELECT 'feedlot_lotes', 'kg_salida_eng', 'decimal(8,2)'
        UNION ALL SELECT 'feedlot_lotes', 'dias_engorde', 'int(11)'
        UNION ALL SELECT 'feedlot_lotes', 'conv_inv', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'conv_eng', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'desperdicio_pct', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'precio_compra', 'decimal(14,2)'
        UNION ALL SELECT 'feedlot_lotes', 'precio_venta_inv', 'decimal(14,2)'
        UNION ALL SELECT 'feedlot_lotes', 'precio_venta_eng', 'decimal(14,2)'
        UNION ALL SELECT 'feedlot_lotes', 'flete_compra_pct', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'flete_venta_pct', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'usd_referencia', 'decimal(10,2)'
        UNION ALL SELECT 'feedlot_lotes', 'notas', 'text'
        UNION ALL SELECT 'feedlot_lotes', 'created_at', 'timestamp'
        UNION ALL SELECT 'ganaderia_egresos', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_egresos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_egresos', 'fecha', 'date'
        UNION ALL SELECT 'ganaderia_egresos', 'categoria', 'varchar(80)'
        UNION ALL SELECT 'ganaderia_egresos', 'subcategoria', 'varchar(120)'
        UNION ALL SELECT 'ganaderia_egresos', 'concepto', 'varchar(200)'
        UNION ALL SELECT 'ganaderia_egresos', 'cantidad', 'decimal(12,3)'
        UNION ALL SELECT 'ganaderia_egresos', 'unidad', 'enum(''kg'',''lt'',''unidad'')'
        UNION ALL SELECT 'ganaderia_egresos', 'precio_unitario', 'decimal(14,4)'
        UNION ALL SELECT 'ganaderia_egresos', 'monto', 'decimal(14,2)'
        UNION ALL SELECT 'ganaderia_egresos', 'moneda', 'enum(''ARS'',''USD'')'
        UNION ALL SELECT 'ganaderia_egresos', 'notas', 'text'
        UNION ALL SELECT 'ganaderia_egresos', 'created_at', 'timestamp'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'categoria', 'varchar(80)'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'subcategoria', 'varchar(120)'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'nombre', 'varchar(200)'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'activo', 'tinyint(1)'
        UNION ALL SELECT 'ganaderia_inventario', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_inventario', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_inventario', 'categoria', 'enum(''vacas_cria'',''vaquillonas'',''novillos'',''terneros'',''terneras'',''toros'',''toros_raza'')'
        UNION ALL SELECT 'ganaderia_inventario', 'cantidad', 'smallint(5) unsigned'
        UNION ALL SELECT 'ganaderia_inventario', 'fecha', 'date'
        UNION ALL SELECT 'ganaderia_inventario', 'ejercicio', 'varchar(10)'
        UNION ALL SELECT 'ganaderia_inventario', 'notas', 'text'
        UNION ALL SELECT 'ganaderia_inventario', 'created_at', 'timestamp'
        UNION ALL SELECT 'ganaderia_movimientos', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_movimientos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_movimientos', 'fecha', 'date'
        UNION ALL SELECT 'ganaderia_movimientos', 'tipo', 'enum(''entrada'',''salida'',''transferencia'',''nacimiento'',''muerte'')'
        UNION ALL SELECT 'ganaderia_movimientos', 'categoria', 'enum(''vacas_cria'',''vaquillonas'',''novillos'',''terneros'',''terneras'',''toros'',''toros_raza'')'
        UNION ALL SELECT 'ganaderia_movimientos', 'cantidad', 'smallint(5) unsigned'
        UNION ALL SELECT 'ganaderia_movimientos', 'precio_cabeza', 'decimal(12,2)'
        UNION ALL SELECT 'ganaderia_movimientos', 'total_kg', 'decimal(10,1)'
        UNION ALL SELECT 'ganaderia_movimientos', 'proveedor_destino', 'varchar(150)'
        UNION ALL SELECT 'ganaderia_movimientos', 'ejercicio', 'varchar(10)'
        UNION ALL SELECT 'ganaderia_movimientos', 'notas', 'text'
        UNION ALL SELECT 'ganaderia_movimientos', 'created_at', 'timestamp'
        UNION ALL SELECT 'ganaderia_pesadas', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_pesadas', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_pesadas', 'fecha', 'date'
        UNION ALL SELECT 'ganaderia_pesadas', 'categoria', 'enum(''vacas_cria'',''vaquillonas'',''novillos'',''terneros'',''terneras'',''toros'')'
        UNION ALL SELECT 'ganaderia_pesadas', 'cantidad_pesada', 'smallint(5) unsigned'
        UNION ALL SELECT 'ganaderia_pesadas', 'peso_promedio_kg', 'decimal(7,1)'
        UNION ALL SELECT 'ganaderia_pesadas', 'peso_total_kg', 'decimal(10,1)'
        UNION ALL SELECT 'ganaderia_pesadas', 'notas', 'text'
        UNION ALL SELECT 'ganaderia_pesadas', 'created_at', 'timestamp'
        UNION ALL SELECT 'ganaderia_reproductivo', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_reproductivo', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_reproductivo', 'ejercicio', 'varchar(10)'
        UNION ALL SELECT 'ganaderia_reproductivo', 'vacas_servicio', 'smallint(5) unsigned'
        UNION ALL SELECT 'ganaderia_reproductivo', 'pct_prenez', 'decimal(5,2)'
        UNION ALL SELECT 'ganaderia_reproductivo', 'pct_destete', 'decimal(5,2)'
        UNION ALL SELECT 'ganaderia_reproductivo', 'terneros_logrados', 'smallint(5) unsigned'
        UNION ALL SELECT 'ganaderia_reproductivo', 'fecha_inicio_servicio', 'date'
        UNION ALL SELECT 'ganaderia_reproductivo', 'fecha_fin_servicio', 'date'
        UNION ALL SELECT 'ganaderia_reproductivo', 'notas', 'text'
        UNION ALL SELECT 'ganaderia_reproductivo', 'created_at', 'timestamp'
        UNION ALL SELECT 'insumos', 'id', 'int(11)'
        UNION ALL SELECT 'insumos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'insumos', 'nombre', 'varchar(150)'
        UNION ALL SELECT 'insumos', 'tipo_insumo', 'enum(''semilla'',''fertilizante'',''agroquimico'',''inoculante'',''otro'')'
        UNION ALL SELECT 'insumos', 'unidad_medida', 'enum(''kg'',''lt'',''dosis'',''bolsa'')'
        UNION ALL SELECT 'insumos', 'precio_estimado_usd', 'decimal(14,4)'
        UNION ALL SELECT 'insumos', 'estado', 'enum(''activo'',''inactivo'')'
        UNION ALL SELECT 'insumos', 'created_at', 'timestamp'
        UNION ALL SELECT 'insumos', 'stock_actual', 'decimal(12,4)'
        UNION ALL SELECT 'insumos', 'unidad_stock', 'varchar(50)'
        UNION ALL SELECT 'insumos', 'fecha_vencimiento', 'date'
        UNION ALL SELECT 'insumos', 'deposito_id', 'int(11)'
        UNION ALL SELECT 'insumos', 'stock_minimo', 'decimal(10,2)'
        UNION ALL SELECT 'lote_historial_campanas', 'id', 'int(11)'
        UNION ALL SELECT 'lote_historial_campanas', 'lote_id', 'int(11)'
        UNION ALL SELECT 'lote_historial_campanas', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'lote_historial_campanas', 'campania', 'varchar(50)'
        UNION ALL SELECT 'lote_historial_campanas', 'cultivo', 'varchar(100)'
        UNION ALL SELECT 'lote_historial_campanas', 'fecha_cierre', 'date'
        UNION ALL SELECT 'lote_historial_campanas', 'kg_total', 'decimal(14,2)'
        UNION ALL SELECT 'lote_historial_campanas', 'ingreso_total', 'decimal(12,2)'
        UNION ALL SELECT 'lote_historial_campanas', 'created_at', 'timestamp'
        UNION ALL SELECT 'motor_consultas_fallidas', 'id', 'int(11)'
        UNION ALL SELECT 'motor_consultas_fallidas', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'motor_consultas_fallidas', 'pregunta', 'varchar(300)'
        UNION ALL SELECT 'motor_consultas_fallidas', 'motivo', 'varchar(120)'
        UNION ALL SELECT 'motor_consultas_fallidas', 'veces', 'int(11)'
        UNION ALL SELECT 'motor_consultas_fallidas', 'creado_at', 'timestamp'
        UNION ALL SELECT 'motor_preferencias', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'motor_preferencias', 'nombre', 'varchar(60)'
        UNION ALL SELECT 'motor_preferencias', 'actualizado_at', 'timestamp'
        UNION ALL SELECT 'operacion_insumos', 'id', 'int(11)'
        UNION ALL SELECT 'operacion_insumos', 'operacion_id', 'int(11)'
        UNION ALL SELECT 'operacion_insumos', 'insumo_id', 'int(11)'
        UNION ALL SELECT 'operacion_insumos', 'cantidad_ha', 'decimal(14,4)'
        UNION ALL SELECT 'operacion_insumos', 'precio_unitario', 'decimal(14,4)'
        UNION ALL SELECT 'operacion_insumos', 'created_at', 'timestamp'
        UNION ALL SELECT 'operacion_insumos', 'nombre_libre', 'varchar(255)'
        UNION ALL SELECT 'operaciones', 'id', 'int(11)'
        UNION ALL SELECT 'operaciones', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'operaciones', 'lote_id', 'int(11)'
        UNION ALL SELECT 'operaciones', 'cultivo_id', 'int(11)'
        UNION ALL SELECT 'operaciones', 'grupo_gasto', 'enum(''siembra'',''cosecha'',''pulverizacion'',''fertilizacion'',''otros'')'
        UNION ALL SELECT 'operaciones', 'tipo_componente', 'enum(''semilla'',''fertilizante'',''agroquimico'',''labor'',''maquinaria'',''insumo'',''multi_insumo'',''receta_labor'')'
        UNION ALL SELECT 'operaciones', 'insumo_id', 'int(11)'
        UNION ALL SELECT 'operaciones', 'proveedor_servicio', 'varchar(255)'
        UNION ALL SELECT 'operaciones', 'cantidad_ha', 'decimal(14,4)'
        UNION ALL SELECT 'operaciones', 'precio_unitario', 'decimal(14,4)'
        UNION ALL SELECT 'operaciones', 'costo_total', 'decimal(12,2)'
        UNION ALL SELECT 'operaciones', 'fecha', 'date'
        UNION ALL SELECT 'operaciones', 'created_at', 'timestamp'
        UNION ALL SELECT 'operaciones', 'campania_operacion', 'varchar(50)'
        UNION ALL SELECT 'operaciones', 'cultivo_operacion', 'varchar(100)'
        UNION ALL SELECT 'operaciones', 'grupo_descripcion', 'varchar(255)'
        UNION ALL SELECT 'operaciones', 'cargas', 'int(11)'
        UNION ALL SELECT 'operaciones', 'hectareas', 'decimal(10,2)'
        UNION ALL SELECT 'operaciones', 'moneda', 'enum(''ARS'',''USD'')'
        UNION ALL SELECT 'produccion_ventas', 'id', 'int(11)'
        UNION ALL SELECT 'produccion_ventas', 'lote_id', 'int(11)'
        UNION ALL SELECT 'produccion_ventas', 'cultivo_id', 'int(11)'
        UNION ALL SELECT 'produccion_ventas', 'kg_cosechados', 'decimal(14,2)'
        UNION ALL SELECT 'produccion_ventas', 'precio_kg', 'decimal(14,4)'
        UNION ALL SELECT 'produccion_ventas', 'ingreso_total', 'decimal(12,2)'
        UNION ALL SELECT 'produccion_ventas', 'fecha_venta', 'date'
        UNION ALL SELECT 'produccion_ventas', 'created_at', 'timestamp'
        UNION ALL SELECT 'produccion_ventas', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'produccion_ventas', 'campania_vendida', 'varchar(50)'
        UNION ALL SELECT 'produccion_ventas', 'cultivo_vendido', 'varchar(100)'
        UNION ALL SELECT 'produccion_ventas', 'notas', 'varchar(255)'
        UNION ALL SELECT 'produccion_ventas', 'moneda', 'enum(''ARS'',''USD'')'
        UNION ALL SELECT 'tambo_calidad', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_calidad', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_calidad', 'fecha', 'date'
        UNION ALL SELECT 'tambo_calidad', 'rcs', 'int(10) unsigned'
        UNION ALL SELECT 'tambo_calidad', 'ufc', 'int(10) unsigned'
        UNION ALL SELECT 'tambo_calidad', 'tenor_graso', 'decimal(4,2)'
        UNION ALL SELECT 'tambo_calidad', 'tenor_prot', 'decimal(4,2)'
        UNION ALL SELECT 'tambo_calidad', 'temp_tank', 'decimal(4,1)'
        UNION ALL SELECT 'tambo_calidad', 'notas', 'text'
        UNION ALL SELECT 'tambo_calidad', 'created_at', 'timestamp'
        UNION ALL SELECT 'tambo_dif_inventario', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_dif_inventario', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_dif_inventario', 'venta_carne_id', 'int(11)'
        UNION ALL SELECT 'tambo_dif_inventario', 'mes_label_act', 'varchar(20)'
        UNION ALL SELECT 'tambo_dif_inventario', 'mes_label_ant', 'varchar(20)'
        UNION ALL SELECT 'tambo_dif_inventario', 'categoria', 'varchar(80)'
        UNION ALL SELECT 'tambo_dif_inventario', 'cant_actual', 'int(11)'
        UNION ALL SELECT 'tambo_dif_inventario', 'cant_anterior', 'int(11)'
        UNION ALL SELECT 'tambo_dif_inventario', 'valor_unitario', 'decimal(14,2)'
        UNION ALL SELECT 'tambo_dif_inventario', 'criterio', 'varchar(150)'
        UNION ALL SELECT 'tambo_dolar_mes', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_dolar_mes', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_dolar_mes', 'mes', 'varchar(7)'
        UNION ALL SELECT 'tambo_dolar_mes', 'dolar_mayorista', 'decimal(12,4)'
        UNION ALL SELECT 'tambo_dolar_mes', 'fuente', 'enum(''api'',''manual'')'
        UNION ALL SELECT 'tambo_dolar_mes', 'creado_en', 'timestamp'
        UNION ALL SELECT 'tambo_dolar_mes', 'actualizado_en', 'timestamp'
        UNION ALL SELECT 'tambo_egresos', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_egresos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_egresos', 'fecha', 'date'
        UNION ALL SELECT 'tambo_egresos', 'categoria', 'varchar(80)'
        UNION ALL SELECT 'tambo_egresos', 'subcategoria', 'varchar(120)'
        UNION ALL SELECT 'tambo_egresos', 'concepto', 'varchar(200)'
        UNION ALL SELECT 'tambo_egresos', 'cantidad', 'decimal(12,3)'
        UNION ALL SELECT 'tambo_egresos', 'unidad', 'enum(''kg'',''lt'',''unidad'')'
        UNION ALL SELECT 'tambo_egresos', 'precio_unitario', 'decimal(14,4)'
        UNION ALL SELECT 'tambo_egresos', 'moneda', 'enum(''ARS'',''USD'')'
        UNION ALL SELECT 'tambo_egresos', 'monto', 'decimal(14,2)'
        UNION ALL SELECT 'tambo_egresos', 'notas', 'text'
        UNION ALL SELECT 'tambo_egresos', 'created_at', 'timestamp'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'categoria', 'varchar(80)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'subcategoria', 'varchar(120)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'nombre', 'varchar(200)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'activo', 'tinyint(1)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'created_at', 'timestamp'
        UNION ALL SELECT 'tambo_produccion', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_produccion', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_produccion', 'fecha', 'date'
        UNION ALL SELECT 'tambo_produccion', 'litros_manana', 'decimal(8,1)'
        UNION ALL SELECT 'tambo_produccion', 'litros_tarde', 'decimal(8,1)'
        UNION ALL SELECT 'tambo_produccion', 'litros_total', 'decimal(8,1)'
        UNION ALL SELECT 'tambo_produccion', 'precio_litro', 'decimal(10,2)'
        UNION ALL SELECT 'tambo_produccion', 'destino', 'enum(''industria'',''auto_consumo'',''descarte'',''buena'',''otra'')'
        UNION ALL SELECT 'tambo_produccion', 'notas', 'text'
        UNION ALL SELECT 'tambo_produccion', 'created_at', 'timestamp'
        UNION ALL SELECT 'tambo_rodeo', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_rodeo', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_rodeo', 'fecha', 'date'
        UNION ALL SELECT 'tambo_rodeo', 'vacas_ordene', 'smallint(5) unsigned'
        UNION ALL SELECT 'tambo_rodeo', 'vacas_secas', 'smallint(5) unsigned'
        UNION ALL SELECT 'tambo_rodeo', 'vaquillonas', 'smallint(5) unsigned'
        UNION ALL SELECT 'tambo_rodeo', 'terneros', 'smallint(5) unsigned'
        UNION ALL SELECT 'tambo_rodeo', 'notas', 'text'
        UNION ALL SELECT 'tambo_rodeo', 'created_at', 'timestamp'
        UNION ALL SELECT 'tambo_ventas_carne', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_ventas_carne', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_ventas_carne', 'fecha', 'date'
        UNION ALL SELECT 'tambo_ventas_carne', 'tipo', 'enum(''diferencia_inventario'',''venta_carne'')'
        UNION ALL SELECT 'tambo_ventas_carne', 'categoria_animal', 'enum(''vaca'',''vaquillona'',''ternero'',''ternera'',''otro'')'
        UNION ALL SELECT 'tambo_ventas_carne', 'cantidad_animales', 'int(11)'
        UNION ALL SELECT 'tambo_ventas_carne', 'kg_vivo', 'decimal(10,2)'
        UNION ALL SELECT 'tambo_ventas_carne', 'precio_kg', 'decimal(10,2)'
        UNION ALL SELECT 'tambo_ventas_carne', 'monto_total', 'decimal(12,2)'
        UNION ALL SELECT 'tambo_ventas_carne', 'monto_original', 'decimal(14,2)'
        UNION ALL SELECT 'tambo_ventas_carne', 'notas', 'text'
        UNION ALL SELECT 'tambo_ventas_carne', 'created_at', 'timestamp'
) e
LEFT JOIN information_schema.COLUMNS c
       ON c.TABLE_SCHEMA = DATABASE()
      AND c.TABLE_NAME   = e.tabla
      AND c.COLUMN_NAME  = e.columna
WHERE c.COLUMN_TYPE IS NULL OR c.COLUMN_TYPE <> e.tipo
ORDER BY e.tabla, e.columna;

-- Columnas de más: están en la base pero no en el esquema esperado.
-- No se borran —pueden ser de algo que todavía no está en el repo—
-- pero conviene saber que están.
SELECT c.TABLE_NAME AS tabla, c.COLUMN_NAME AS columna, c.COLUMN_TYPE AS tipo
FROM information_schema.COLUMNS c
JOIN information_schema.TABLES t
       ON t.TABLE_SCHEMA = c.TABLE_SCHEMA AND t.TABLE_NAME = c.TABLE_NAME
      AND t.TABLE_TYPE = 'BASE TABLE'
LEFT JOIN (
        SELECT 'users' AS tabla, 'id' AS columna, 'int(11)' AS tipo
        UNION ALL SELECT 'users', 'username', 'varchar(50)'
        UNION ALL SELECT 'users', 'email', 'varchar(100)'
        UNION ALL SELECT 'users', 'password_hash', 'varchar(255)'
        UNION ALL SELECT 'users', 'role', 'enum(''admin'',''user'')'
        UNION ALL SELECT 'users', 'status', 'enum(''pending'',''active'')'
        UNION ALL SELECT 'users', 'created_at', 'timestamp'
        UNION ALL SELECT 'users', 'has_agricultura', 'tinyint(1)'
        UNION ALL SELECT 'users', 'has_tambo', 'tinyint(1)'
        UNION ALL SELECT 'users', 'has_ganaderia', 'tinyint(1)'
        UNION ALL SELECT 'users', 'reset_token', 'varchar(255)'
        UNION ALL SELECT 'users', 'reset_expires', 'datetime'
        UNION ALL SELECT 'users', 'solo_lectura', 'tinyint(1)'
        UNION ALL SELECT 'cultivos', 'id', 'int(11)'
        UNION ALL SELECT 'cultivos', 'lote_id', 'int(11)'
        UNION ALL SELECT 'cultivos', 'nombre', 'varchar(100)'
        UNION ALL SELECT 'cultivos', 'fecha_siembra', 'date'
        UNION ALL SELECT 'cultivos', 'fecha_cosecha_esperada', 'date'
        UNION ALL SELECT 'cultivos', 'estado', 'enum(''activo'',''cosechado'',''perdido'')'
        UNION ALL SELECT 'cultivos', 'created_at', 'timestamp'
        UNION ALL SELECT 'cultivos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'cultivos', 'ciclo', 'varchar(50)'
        UNION ALL SELECT 'lotes', 'id', 'int(11)'
        UNION ALL SELECT 'lotes', 'nombre', 'varchar(100)'
        UNION ALL SELECT 'lotes', 'superficie', 'decimal(10,2)'
        UNION ALL SELECT 'lotes', 'ubicacion', 'varchar(255)'
        UNION ALL SELECT 'lotes', 'tipo_suelo', 'varchar(100)'
        UNION ALL SELECT 'lotes', 'created_at', 'timestamp'
        UNION ALL SELECT 'lotes', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'lotes', 'latitud', 'decimal(10,8)'
        UNION ALL SELECT 'lotes', 'longitud', 'decimal(11,8)'
        UNION ALL SELECT 'lotes', 'tenencia', 'enum(''propio'',''alquilado'')'
        UNION ALL SELECT 'lotes', 'costo_alquiler_tns_ha', 'decimal(14,4)'
        UNION ALL SELECT 'lotes', 'campania', 'varchar(50)'
        UNION ALL SELECT 'lotes', 'cultivo_actual', 'varchar(100)'
        UNION ALL SELECT 'depositos', 'id', 'int(11)'
        UNION ALL SELECT 'depositos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'depositos', 'nombre', 'varchar(100)'
        UNION ALL SELECT 'depositos', 'descripcion', 'varchar(255)'
        UNION ALL SELECT 'depositos', 'ubicacion', 'varchar(255)'
        UNION ALL SELECT 'depositos', 'created_at', 'timestamp'
        UNION ALL SELECT 'alquileres', 'id', 'int(11)'
        UNION ALL SELECT 'alquileres', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'alquileres', 'lote_id', 'int(11)'
        UNION ALL SELECT 'alquileres', 'cultivo_id', 'int(11)'
        UNION ALL SELECT 'alquileres', 'nivel_imputacion', 'enum(''lote'',''cultivo'',''campania'')'
        UNION ALL SELECT 'alquileres', 'campania', 'varchar(50)'
        UNION ALL SELECT 'alquileres', 'fecha_pago', 'date'
        UNION ALL SELECT 'alquileres', 'monto_pagado', 'decimal(14,4)'
        UNION ALL SELECT 'alquileres', 'moneda', 'enum(''USD'',''ARS'')'
        UNION ALL SELECT 'alquileres', 'notas', 'text'
        UNION ALL SELECT 'alquileres', 'created_at', 'timestamp'
        UNION ALL SELECT 'cotizaciones_siogranos', 'id', 'int(11)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'fecha', 'date'
        UNION ALL SELECT 'cotizaciones_siogranos', 'cultivo', 'varchar(50)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'producto_id', 'varchar(30)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'zona', 'varchar(80)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'zona_id', 'varchar(10)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'precio_promedio', 'decimal(12,2)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'precio_minimo', 'decimal(12,2)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'precio_maximo', 'decimal(12,2)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'precio_modal', 'decimal(12,2)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'moneda', 'varchar(5)'
        UNION ALL SELECT 'cotizaciones_siogranos', 'fecha_actualizacion', 'datetime'
        UNION ALL SELECT 'feedlot_alimentos', 'id', 'int(11)'
        UNION ALL SELECT 'feedlot_alimentos', 'lote_id', 'int(11)'
        UNION ALL SELECT 'feedlot_alimentos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'feedlot_alimentos', 'fase', 'enum(''invernada'',''engorde'')'
        UNION ALL SELECT 'feedlot_alimentos', 'nombre', 'varchar(100)'
        UNION ALL SELECT 'feedlot_alimentos', 'kg_x_dia', 'decimal(8,3)'
        UNION ALL SELECT 'feedlot_alimentos', 'precio_kg', 'decimal(10,2)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'id', 'int(11)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'lote_id', 'int(11)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'concepto', 'varchar(100)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'categoria', 'varchar(30)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'cantidad', 'decimal(10,2)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'precio_unitario', 'decimal(14,2)'
        UNION ALL SELECT 'feedlot_costos_fijos', 'monto_mensual', 'decimal(14,2)'
        UNION ALL SELECT 'feedlot_lotes', 'id', 'int(11)'
        UNION ALL SELECT 'feedlot_lotes', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'feedlot_lotes', 'nombre', 'varchar(100)'
        UNION ALL SELECT 'feedlot_lotes', 'fecha_inicio', 'date'
        UNION ALL SELECT 'feedlot_lotes', 'cant_animales', 'int(11)'
        UNION ALL SELECT 'feedlot_lotes', 'pct_invernada', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'pct_engorde', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'kg_entrada_inv', 'decimal(8,2)'
        UNION ALL SELECT 'feedlot_lotes', 'kg_salida_inv', 'decimal(8,2)'
        UNION ALL SELECT 'feedlot_lotes', 'dias_invernada', 'int(11)'
        UNION ALL SELECT 'feedlot_lotes', 'kg_entrada_eng', 'decimal(8,2)'
        UNION ALL SELECT 'feedlot_lotes', 'kg_salida_eng', 'decimal(8,2)'
        UNION ALL SELECT 'feedlot_lotes', 'dias_engorde', 'int(11)'
        UNION ALL SELECT 'feedlot_lotes', 'conv_inv', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'conv_eng', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'desperdicio_pct', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'precio_compra', 'decimal(14,2)'
        UNION ALL SELECT 'feedlot_lotes', 'precio_venta_inv', 'decimal(14,2)'
        UNION ALL SELECT 'feedlot_lotes', 'precio_venta_eng', 'decimal(14,2)'
        UNION ALL SELECT 'feedlot_lotes', 'flete_compra_pct', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'flete_venta_pct', 'decimal(5,2)'
        UNION ALL SELECT 'feedlot_lotes', 'usd_referencia', 'decimal(10,2)'
        UNION ALL SELECT 'feedlot_lotes', 'notas', 'text'
        UNION ALL SELECT 'feedlot_lotes', 'created_at', 'timestamp'
        UNION ALL SELECT 'ganaderia_egresos', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_egresos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_egresos', 'fecha', 'date'
        UNION ALL SELECT 'ganaderia_egresos', 'categoria', 'varchar(80)'
        UNION ALL SELECT 'ganaderia_egresos', 'subcategoria', 'varchar(120)'
        UNION ALL SELECT 'ganaderia_egresos', 'concepto', 'varchar(200)'
        UNION ALL SELECT 'ganaderia_egresos', 'cantidad', 'decimal(12,3)'
        UNION ALL SELECT 'ganaderia_egresos', 'unidad', 'enum(''kg'',''lt'',''unidad'')'
        UNION ALL SELECT 'ganaderia_egresos', 'precio_unitario', 'decimal(14,4)'
        UNION ALL SELECT 'ganaderia_egresos', 'monto', 'decimal(14,2)'
        UNION ALL SELECT 'ganaderia_egresos', 'moneda', 'enum(''ARS'',''USD'')'
        UNION ALL SELECT 'ganaderia_egresos', 'notas', 'text'
        UNION ALL SELECT 'ganaderia_egresos', 'created_at', 'timestamp'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'categoria', 'varchar(80)'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'subcategoria', 'varchar(120)'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'nombre', 'varchar(200)'
        UNION ALL SELECT 'ganaderia_egresos_conceptos', 'activo', 'tinyint(1)'
        UNION ALL SELECT 'ganaderia_inventario', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_inventario', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_inventario', 'categoria', 'enum(''vacas_cria'',''vaquillonas'',''novillos'',''terneros'',''terneras'',''toros'',''toros_raza'')'
        UNION ALL SELECT 'ganaderia_inventario', 'cantidad', 'smallint(5) unsigned'
        UNION ALL SELECT 'ganaderia_inventario', 'fecha', 'date'
        UNION ALL SELECT 'ganaderia_inventario', 'ejercicio', 'varchar(10)'
        UNION ALL SELECT 'ganaderia_inventario', 'notas', 'text'
        UNION ALL SELECT 'ganaderia_inventario', 'created_at', 'timestamp'
        UNION ALL SELECT 'ganaderia_movimientos', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_movimientos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_movimientos', 'fecha', 'date'
        UNION ALL SELECT 'ganaderia_movimientos', 'tipo', 'enum(''entrada'',''salida'',''transferencia'',''nacimiento'',''muerte'')'
        UNION ALL SELECT 'ganaderia_movimientos', 'categoria', 'enum(''vacas_cria'',''vaquillonas'',''novillos'',''terneros'',''terneras'',''toros'',''toros_raza'')'
        UNION ALL SELECT 'ganaderia_movimientos', 'cantidad', 'smallint(5) unsigned'
        UNION ALL SELECT 'ganaderia_movimientos', 'precio_cabeza', 'decimal(12,2)'
        UNION ALL SELECT 'ganaderia_movimientos', 'total_kg', 'decimal(10,1)'
        UNION ALL SELECT 'ganaderia_movimientos', 'proveedor_destino', 'varchar(150)'
        UNION ALL SELECT 'ganaderia_movimientos', 'ejercicio', 'varchar(10)'
        UNION ALL SELECT 'ganaderia_movimientos', 'notas', 'text'
        UNION ALL SELECT 'ganaderia_movimientos', 'created_at', 'timestamp'
        UNION ALL SELECT 'ganaderia_pesadas', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_pesadas', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_pesadas', 'fecha', 'date'
        UNION ALL SELECT 'ganaderia_pesadas', 'categoria', 'enum(''vacas_cria'',''vaquillonas'',''novillos'',''terneros'',''terneras'',''toros'')'
        UNION ALL SELECT 'ganaderia_pesadas', 'cantidad_pesada', 'smallint(5) unsigned'
        UNION ALL SELECT 'ganaderia_pesadas', 'peso_promedio_kg', 'decimal(7,1)'
        UNION ALL SELECT 'ganaderia_pesadas', 'peso_total_kg', 'decimal(10,1)'
        UNION ALL SELECT 'ganaderia_pesadas', 'notas', 'text'
        UNION ALL SELECT 'ganaderia_pesadas', 'created_at', 'timestamp'
        UNION ALL SELECT 'ganaderia_reproductivo', 'id', 'int(11)'
        UNION ALL SELECT 'ganaderia_reproductivo', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'ganaderia_reproductivo', 'ejercicio', 'varchar(10)'
        UNION ALL SELECT 'ganaderia_reproductivo', 'vacas_servicio', 'smallint(5) unsigned'
        UNION ALL SELECT 'ganaderia_reproductivo', 'pct_prenez', 'decimal(5,2)'
        UNION ALL SELECT 'ganaderia_reproductivo', 'pct_destete', 'decimal(5,2)'
        UNION ALL SELECT 'ganaderia_reproductivo', 'terneros_logrados', 'smallint(5) unsigned'
        UNION ALL SELECT 'ganaderia_reproductivo', 'fecha_inicio_servicio', 'date'
        UNION ALL SELECT 'ganaderia_reproductivo', 'fecha_fin_servicio', 'date'
        UNION ALL SELECT 'ganaderia_reproductivo', 'notas', 'text'
        UNION ALL SELECT 'ganaderia_reproductivo', 'created_at', 'timestamp'
        UNION ALL SELECT 'insumos', 'id', 'int(11)'
        UNION ALL SELECT 'insumos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'insumos', 'nombre', 'varchar(150)'
        UNION ALL SELECT 'insumos', 'tipo_insumo', 'enum(''semilla'',''fertilizante'',''agroquimico'',''inoculante'',''otro'')'
        UNION ALL SELECT 'insumos', 'unidad_medida', 'enum(''kg'',''lt'',''dosis'',''bolsa'')'
        UNION ALL SELECT 'insumos', 'precio_estimado_usd', 'decimal(14,4)'
        UNION ALL SELECT 'insumos', 'estado', 'enum(''activo'',''inactivo'')'
        UNION ALL SELECT 'insumos', 'created_at', 'timestamp'
        UNION ALL SELECT 'insumos', 'stock_actual', 'decimal(12,4)'
        UNION ALL SELECT 'insumos', 'unidad_stock', 'varchar(50)'
        UNION ALL SELECT 'insumos', 'fecha_vencimiento', 'date'
        UNION ALL SELECT 'insumos', 'deposito_id', 'int(11)'
        UNION ALL SELECT 'insumos', 'stock_minimo', 'decimal(10,2)'
        UNION ALL SELECT 'lote_historial_campanas', 'id', 'int(11)'
        UNION ALL SELECT 'lote_historial_campanas', 'lote_id', 'int(11)'
        UNION ALL SELECT 'lote_historial_campanas', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'lote_historial_campanas', 'campania', 'varchar(50)'
        UNION ALL SELECT 'lote_historial_campanas', 'cultivo', 'varchar(100)'
        UNION ALL SELECT 'lote_historial_campanas', 'fecha_cierre', 'date'
        UNION ALL SELECT 'lote_historial_campanas', 'kg_total', 'decimal(14,2)'
        UNION ALL SELECT 'lote_historial_campanas', 'ingreso_total', 'decimal(12,2)'
        UNION ALL SELECT 'lote_historial_campanas', 'created_at', 'timestamp'
        UNION ALL SELECT 'motor_consultas_fallidas', 'id', 'int(11)'
        UNION ALL SELECT 'motor_consultas_fallidas', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'motor_consultas_fallidas', 'pregunta', 'varchar(300)'
        UNION ALL SELECT 'motor_consultas_fallidas', 'motivo', 'varchar(120)'
        UNION ALL SELECT 'motor_consultas_fallidas', 'veces', 'int(11)'
        UNION ALL SELECT 'motor_consultas_fallidas', 'creado_at', 'timestamp'
        UNION ALL SELECT 'motor_preferencias', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'motor_preferencias', 'nombre', 'varchar(60)'
        UNION ALL SELECT 'motor_preferencias', 'actualizado_at', 'timestamp'
        UNION ALL SELECT 'operacion_insumos', 'id', 'int(11)'
        UNION ALL SELECT 'operacion_insumos', 'operacion_id', 'int(11)'
        UNION ALL SELECT 'operacion_insumos', 'insumo_id', 'int(11)'
        UNION ALL SELECT 'operacion_insumos', 'cantidad_ha', 'decimal(14,4)'
        UNION ALL SELECT 'operacion_insumos', 'precio_unitario', 'decimal(14,4)'
        UNION ALL SELECT 'operacion_insumos', 'created_at', 'timestamp'
        UNION ALL SELECT 'operacion_insumos', 'nombre_libre', 'varchar(255)'
        UNION ALL SELECT 'operaciones', 'id', 'int(11)'
        UNION ALL SELECT 'operaciones', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'operaciones', 'lote_id', 'int(11)'
        UNION ALL SELECT 'operaciones', 'cultivo_id', 'int(11)'
        UNION ALL SELECT 'operaciones', 'grupo_gasto', 'enum(''siembra'',''cosecha'',''pulverizacion'',''fertilizacion'',''otros'')'
        UNION ALL SELECT 'operaciones', 'tipo_componente', 'enum(''semilla'',''fertilizante'',''agroquimico'',''labor'',''maquinaria'',''insumo'',''multi_insumo'',''receta_labor'')'
        UNION ALL SELECT 'operaciones', 'insumo_id', 'int(11)'
        UNION ALL SELECT 'operaciones', 'proveedor_servicio', 'varchar(255)'
        UNION ALL SELECT 'operaciones', 'cantidad_ha', 'decimal(14,4)'
        UNION ALL SELECT 'operaciones', 'precio_unitario', 'decimal(14,4)'
        UNION ALL SELECT 'operaciones', 'costo_total', 'decimal(12,2)'
        UNION ALL SELECT 'operaciones', 'fecha', 'date'
        UNION ALL SELECT 'operaciones', 'created_at', 'timestamp'
        UNION ALL SELECT 'operaciones', 'campania_operacion', 'varchar(50)'
        UNION ALL SELECT 'operaciones', 'cultivo_operacion', 'varchar(100)'
        UNION ALL SELECT 'operaciones', 'grupo_descripcion', 'varchar(255)'
        UNION ALL SELECT 'operaciones', 'cargas', 'int(11)'
        UNION ALL SELECT 'operaciones', 'hectareas', 'decimal(10,2)'
        UNION ALL SELECT 'operaciones', 'moneda', 'enum(''ARS'',''USD'')'
        UNION ALL SELECT 'produccion_ventas', 'id', 'int(11)'
        UNION ALL SELECT 'produccion_ventas', 'lote_id', 'int(11)'
        UNION ALL SELECT 'produccion_ventas', 'cultivo_id', 'int(11)'
        UNION ALL SELECT 'produccion_ventas', 'kg_cosechados', 'decimal(14,2)'
        UNION ALL SELECT 'produccion_ventas', 'precio_kg', 'decimal(14,4)'
        UNION ALL SELECT 'produccion_ventas', 'ingreso_total', 'decimal(12,2)'
        UNION ALL SELECT 'produccion_ventas', 'fecha_venta', 'date'
        UNION ALL SELECT 'produccion_ventas', 'created_at', 'timestamp'
        UNION ALL SELECT 'produccion_ventas', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'produccion_ventas', 'campania_vendida', 'varchar(50)'
        UNION ALL SELECT 'produccion_ventas', 'cultivo_vendido', 'varchar(100)'
        UNION ALL SELECT 'produccion_ventas', 'notas', 'varchar(255)'
        UNION ALL SELECT 'produccion_ventas', 'moneda', 'enum(''ARS'',''USD'')'
        UNION ALL SELECT 'tambo_calidad', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_calidad', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_calidad', 'fecha', 'date'
        UNION ALL SELECT 'tambo_calidad', 'rcs', 'int(10) unsigned'
        UNION ALL SELECT 'tambo_calidad', 'ufc', 'int(10) unsigned'
        UNION ALL SELECT 'tambo_calidad', 'tenor_graso', 'decimal(4,2)'
        UNION ALL SELECT 'tambo_calidad', 'tenor_prot', 'decimal(4,2)'
        UNION ALL SELECT 'tambo_calidad', 'temp_tank', 'decimal(4,1)'
        UNION ALL SELECT 'tambo_calidad', 'notas', 'text'
        UNION ALL SELECT 'tambo_calidad', 'created_at', 'timestamp'
        UNION ALL SELECT 'tambo_dif_inventario', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_dif_inventario', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_dif_inventario', 'venta_carne_id', 'int(11)'
        UNION ALL SELECT 'tambo_dif_inventario', 'mes_label_act', 'varchar(20)'
        UNION ALL SELECT 'tambo_dif_inventario', 'mes_label_ant', 'varchar(20)'
        UNION ALL SELECT 'tambo_dif_inventario', 'categoria', 'varchar(80)'
        UNION ALL SELECT 'tambo_dif_inventario', 'cant_actual', 'int(11)'
        UNION ALL SELECT 'tambo_dif_inventario', 'cant_anterior', 'int(11)'
        UNION ALL SELECT 'tambo_dif_inventario', 'valor_unitario', 'decimal(14,2)'
        UNION ALL SELECT 'tambo_dif_inventario', 'criterio', 'varchar(150)'
        UNION ALL SELECT 'tambo_dolar_mes', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_dolar_mes', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_dolar_mes', 'mes', 'varchar(7)'
        UNION ALL SELECT 'tambo_dolar_mes', 'dolar_mayorista', 'decimal(12,4)'
        UNION ALL SELECT 'tambo_dolar_mes', 'fuente', 'enum(''api'',''manual'')'
        UNION ALL SELECT 'tambo_dolar_mes', 'creado_en', 'timestamp'
        UNION ALL SELECT 'tambo_dolar_mes', 'actualizado_en', 'timestamp'
        UNION ALL SELECT 'tambo_egresos', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_egresos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_egresos', 'fecha', 'date'
        UNION ALL SELECT 'tambo_egresos', 'categoria', 'varchar(80)'
        UNION ALL SELECT 'tambo_egresos', 'subcategoria', 'varchar(120)'
        UNION ALL SELECT 'tambo_egresos', 'concepto', 'varchar(200)'
        UNION ALL SELECT 'tambo_egresos', 'cantidad', 'decimal(12,3)'
        UNION ALL SELECT 'tambo_egresos', 'unidad', 'enum(''kg'',''lt'',''unidad'')'
        UNION ALL SELECT 'tambo_egresos', 'precio_unitario', 'decimal(14,4)'
        UNION ALL SELECT 'tambo_egresos', 'moneda', 'enum(''ARS'',''USD'')'
        UNION ALL SELECT 'tambo_egresos', 'monto', 'decimal(14,2)'
        UNION ALL SELECT 'tambo_egresos', 'notas', 'text'
        UNION ALL SELECT 'tambo_egresos', 'created_at', 'timestamp'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'categoria', 'varchar(80)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'subcategoria', 'varchar(120)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'nombre', 'varchar(200)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'activo', 'tinyint(1)'
        UNION ALL SELECT 'tambo_egresos_conceptos', 'created_at', 'timestamp'
        UNION ALL SELECT 'tambo_produccion', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_produccion', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_produccion', 'fecha', 'date'
        UNION ALL SELECT 'tambo_produccion', 'litros_manana', 'decimal(8,1)'
        UNION ALL SELECT 'tambo_produccion', 'litros_tarde', 'decimal(8,1)'
        UNION ALL SELECT 'tambo_produccion', 'litros_total', 'decimal(8,1)'
        UNION ALL SELECT 'tambo_produccion', 'precio_litro', 'decimal(10,2)'
        UNION ALL SELECT 'tambo_produccion', 'destino', 'enum(''industria'',''auto_consumo'',''descarte'',''buena'',''otra'')'
        UNION ALL SELECT 'tambo_produccion', 'notas', 'text'
        UNION ALL SELECT 'tambo_produccion', 'created_at', 'timestamp'
        UNION ALL SELECT 'tambo_rodeo', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_rodeo', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_rodeo', 'fecha', 'date'
        UNION ALL SELECT 'tambo_rodeo', 'vacas_ordene', 'smallint(5) unsigned'
        UNION ALL SELECT 'tambo_rodeo', 'vacas_secas', 'smallint(5) unsigned'
        UNION ALL SELECT 'tambo_rodeo', 'vaquillonas', 'smallint(5) unsigned'
        UNION ALL SELECT 'tambo_rodeo', 'terneros', 'smallint(5) unsigned'
        UNION ALL SELECT 'tambo_rodeo', 'notas', 'text'
        UNION ALL SELECT 'tambo_rodeo', 'created_at', 'timestamp'
        UNION ALL SELECT 'tambo_ventas_carne', 'id', 'int(11)'
        UNION ALL SELECT 'tambo_ventas_carne', 'usuario_id', 'int(11)'
        UNION ALL SELECT 'tambo_ventas_carne', 'fecha', 'date'
        UNION ALL SELECT 'tambo_ventas_carne', 'tipo', 'enum(''diferencia_inventario'',''venta_carne'')'
        UNION ALL SELECT 'tambo_ventas_carne', 'categoria_animal', 'enum(''vaca'',''vaquillona'',''ternero'',''ternera'',''otro'')'
        UNION ALL SELECT 'tambo_ventas_carne', 'cantidad_animales', 'int(11)'
        UNION ALL SELECT 'tambo_ventas_carne', 'kg_vivo', 'decimal(10,2)'
        UNION ALL SELECT 'tambo_ventas_carne', 'precio_kg', 'decimal(10,2)'
        UNION ALL SELECT 'tambo_ventas_carne', 'monto_total', 'decimal(12,2)'
        UNION ALL SELECT 'tambo_ventas_carne', 'monto_original', 'decimal(14,2)'
        UNION ALL SELECT 'tambo_ventas_carne', 'notas', 'text'
        UNION ALL SELECT 'tambo_ventas_carne', 'created_at', 'timestamp'
) e ON e.tabla = c.TABLE_NAME AND e.columna = c.COLUMN_NAME
WHERE c.TABLE_SCHEMA = DATABASE()
  AND c.TABLE_NAME NOT LIKE '\_%'
  AND e.columna IS NULL
ORDER BY c.TABLE_NAME, c.COLUMN_NAME;

-- Colación: tiene que volver VACÍA. Una tabla con colación distinta hace
-- que un JOIN por texto contra otra tabla aborte con 1267 Illegal mix of
-- collations. Ya tiró el tablero una vez.
--
-- OJO: esto lo DETECTA pero no lo arregla. Convertir una tabla que ya
-- existe reescribe sus índices, que es una operación bastante más pesada
-- que todo lo demás de este archivo, y no corresponde meterla acá de
-- prepo. Si devuelve filas, correr normalize_collation_utf8mb4_unicode_ci.sql
SELECT TABLE_NAME AS tabla, TABLE_COLLATION AS colacion
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_TYPE = 'BASE TABLE'
  AND TABLE_NAME NOT LIKE '\_%'
  AND TABLE_COLLATION <> 'utf8mb4_unicode_ci'
ORDER BY TABLE_NAME;
